#ifndef MAIN_HPP
#define MAIN_HPP

#include "SDL2/SDL.h"

/// IMPLEMENT PUSH TIMES TO LEADERBOARD
/// IMPLEMENT LOAD MISSION FROM FILE
/// IMPLEMENT LOAD DIFFICULTY SETTINGS

int SDL_main(int argc, char* argv[]);

#endif /* MAIN_HPP */