#ifndef MAIN_HPP
#define MAIN_HPP

#include "SDL2/SDL.h"

/// ADD COLLISION TO STATE TO SIGNAL THAT A MOB CAN NO LONGER WALK THE WAY IT IS HEADING
/// IF COLLIDING A MOB SHOULD GO IN THE OTHER DIRECTION TOWARDS THE PLAYER
/// IF STILL COLLIDING THE MOB SHOULD GO IN THE SMALLEST DIRECTION AWAY FROM THE PLAYER
/// IF STILL COLLIDING THE MOB SHOULD GO THE FURTHEST DIRECTION AWAY FROM THE PLAYER

/// IMPLEMENT GAME CONTROLLER SUPPORT

/// IMPLEMENT BLOCKS AND STAMINA

int SDL_main(int argc, char* argv[]);

#endif /* MAIN_HPP */